### ISSUE TITLE
how did the address such as "uuid_11aa22bb_cac7_459a_a759_2eab2efd02ae"  in axi_mem_if_SP.xml come from?

### ISSUE THREAD

**Issue by brandot4life** [kactus2/pulpinoexperiment#2]
As title,
I'd really like to know how did the value and parameterId come from? Is there any meaning for it?
Thanks in advance

BRs

**Comment by epekkar** [comment]
Hi,

`uuid_11aa22bb_cac7_459a_a759_2eab2efd02ae` is a [Universally Unique Identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier) for the parameter AXI4_ADDRESS_WIDTH. When used in an expression within the component axi_mem_if_SP, it evaluates to the value of the parameter (32 by default).

**Comment by brandot4life** [comment]
Hi,
 So it can be another UUID that we generated, right? Only if we make sure
that it's unique
Thanks in advance

BRs

epekkar ***@***.***> 於 2023年11月13日 週一 下午12:08寫道：

**Comment by epekkar** [comment]
The IP-XACT standard requires that parameters within a component have unique ids for unambiguity. The means of selecting the ids is not restricted in any ways i.e. you could use whatever ids as long as there are no duplicates. The XML files in this repository are created with the Kactus2 tool which automatically generates UUIDs for parameters.

**Comment by brandot4life** [comment]
hi,
  Thanks for the explanation. It's really clear. But I'd like to ask why we
use UUID in ipxact:value in ipxact:moduleParameter instead of the real
value like 32 in AXI4_ADDRESS_WIDTH case?
Thanks in advance

BRs

epekkar ***@***.***> 於 2023年11月13日 週一 下午1:51寫道：

**Comment by epekkar** [comment]
That is to ensure the same value for the (component) parameter which controls e.g. port widths and the module parameter which adds details for RTL .

**Comment by brandot4life** [comment]
Hi,
Thanks a lot for the explanation!!! I'd like to ask that are you the author
of the ipxact structure in the pulpinoexperiment project?
I've been surveying the ipxact file recently and wondering why some SV file
don't have its ipxact file, such as data about dp_ram?
Thanks in advance~

BRs

epekkar ***@***.***> 於 2023年11月13日 週一 下午2:00寫道：

**Comment by epekkar** [comment]
That is mostly to save time on creating the IP-XACT files. The objective in this project was to create a meaningful set of IP-XACT files from the top down. So most of the omitted RTL files are either low in the hierarchy or not that important for the structural description of the system.
